services:
  - type: web
    name: blockFiles
    runtime: node
    repo: https://github.com/Sandesh13fr/blockFiles
    branch: deployment
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
